# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
        matrix:
          include:
            - boardfamily: meson64
              branch: current
              representative: aml-s9xx-box
        fail-fast: false
    runs-on: ubuntu-22.04
    env:
      BOARD_FAMILY: ${{ matrix.boardfamily }}
      BRANCH: ${{ matrix.branch }}
      BOARD_NAME: ${{ matrix.representative }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: armbian/build
      - uses: actions/checkout@v3
        with:
          path: utils

      - name: Build Kernel
        run: |
          # Copy helper files.
          cp utils/* ./

          # Remove disabling DEBUG_INFO.
          sed -i '/kernel_config_set_n DEBUG_INFO/d' lib/functions/compilation/armbian-kernel.sh

          # Enable BTF.
          sed -i '/CONFIG_DEBUG_INFO/d' config/kernel/linux-"$BOARD_FAMILY"-"$BRANCH".config
          echo "CONFIG_DEBUG_INFO=y
          CONFIG_DEBUG_INFO_DWARF4=y
          CONFIG_PAHOLE_HAS_SPLIT_BTF=y
          CONFIG_DEBUG_INFO_BTF_MODULES=y
          CONFIG_DEBUG_INFO_BTF=y" >> config/kernel/linux-"$BOARD_FAMILY"-"$BRANCH".config

          # Compile kernel.
          ./compile.sh BUILD_ONLY=default KERNEL_ONLY=no KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=no BOARD="$BOARD_NAME" BRANCH="$BRANCH" RELEASE=jammy INSTALL_HEADERS=yes KERNEL_GIT=SHALLOW 
      - name: upload result
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: ${{ github.workspace }}/output

