name: CI
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
        matrix:
          include:
            - boardfamily: meson64
              branch: current
              representative: aml-s9xx-box
        fail-fast: false
    runs-on: ubuntu-22.04
    env:
      BOARD_FAMILY: ${{ matrix.boardfamily }}
      BRANCH: ${{ matrix.branch }}
      BOARD_NAME: ${{ matrix.representative }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: armbian/build
          ref: 'master'
      - uses: actions/checkout@v3
        with:
          path: utils
      - name: Build Kernel
        run: |
          # Copy helper files.
          cp -r utils/* ./
          # Compile kernel.
          ./compile.sh docker BUILD_ONLY=default KERNEL_ONLY=no KERNEL_CONFIGURE=no BUILD_MINIMAL=no BUILD_DESKTOP=no BOARD="$BOARD_NAME" BRANCH="$BRANCH" RELEASE=jammy INSTALL_HEADERS=yes
      - name: upload result
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: ${{ github.workspace }}/output

